[package]
name = "poker"
type = "contract"
authors = [""]
compiler_version = "0.16.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.8.14", directory="yarn-project/aztec-nr/aztec" }
